### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jasonghlin**
林干紘
http://52.38.144.253:8000
http://52.38.144.253:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Take care of details: border, padding, spacing.
- Layout width exceeds screen width slightly in small to middle size of devices.
52 38 144 253_8000_attraction_2

**Comment by jasonghlin** [comment]
I have completed the modifications for the layout of image and input. Regarding the issue where the layout width slightly exceeds the screen width on small to medium-sized devices, I still cannot see the scroll on my device. If you continue to experience this issue, please let me know. Thank you.
Screenshot 2024-06-10 at 5 26 29 PM

**Review by cwpeng — CHANGES_REQUESTED** [review]
Try to take another attention on date input border.

**Comment by jasonghlin** [comment]
I'm very sorry for overlooking this basic detail. I have now corrected it.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
